### ISSUE TITLE
Questions about circuit design.

### ISSUE THREAD

**Issue by fitz0401** [xevisalle/zpie#1]
ZPiE is the best ZKP lib I've ever seen for IoT devices, especially for those low-resource devices.
I've read the article, but I still felt confused about the circuit design. I wonder if there are any detailed information about the usage of GMP, and how can I modify the "circuit.c" and "parser.c" for my own circuit? I'm eager to learn more about it.

**Comment by xevisalle** [comment]
Unfortunately I never had the time to write down a proper documentation. However, feel free to ask any doubts you might have. `circuit.c` is basically where you need to define your circuit, the first function to be called will be `void circuit()`. You can write in there your circuit. You have some examples there, you can call the provided `mimc7` and `verify_eddsa` circuits (what is commonly known as gadget), or you can write your own circuits using the constraint API, defined in `parser.c`.

A basic example is this one:

```
element x, y, z;
	init(&x);

	mul(&factor1, &u1, &v2);
```

**Comment by xevisalle** [comment]
Hey, thanks for your questions.

1) About this, yes, it is a bug that I tried to fix with this temporary patch, but it seems that you also need to set a big value to `N`. Indeed, the problem comes when using small values. My intuition is that it comes from the Heap Sorting algorithm needed to perform the Bos-Coster multiexponentiation. I will need to add tests and work further on this. By now, you can also try to use the multiexponentiation algorithm provided by the MCL library (which happens to be a bit less efficient). Just recompile with:

   `make single MULEXP=MCL_MULEXP`

2) Sadly I haven't implemented comparators. But you can take this code as a good reference: https://github.com/iden3/circomlib/blob/master/circuits/comparators.circom

   It should be pretty simple to implement, as the Num2Bit function that they use is already implemented for ZPiE here:
https://github.com/xevisalle/zpie/blob/7e944d43ba34d9747fafe4ef691c575ba8fd9287/circuits/eddsa.c#L129C8-L129C8

   Once you have these functions, and for what concerns the circuit workflow, the idea is that *if* an input is within the range, the proof will verify, and won't verify otherwise. It's like, you don't really need to "print" anything, simply check whether the proof is verified or not.

   On the other hand, you can use *if*, *else*, *for*, etc. when writing the circuit, but these won't be part of the arithmetic circuit, they will be executed when *compiling* that circuit (e.g. you can write a loop that adds X constraints to the circuit).

Hope this helps! :)

**Comment by xevisalle** [comment]
It is correct as long as you keep in mind that the condition at the begining is NOT in-circuit. For in-circuit comparisions you will need to write the comparision utility using logic gates.

**Comment by xevisalle** [comment]
Yes it can be done. Actually I did tried it out time ago. Their `gamma_abc` is the array that we call in ZPiE `vk.vk1[]`.

**Comment by xevisalle** [comment]
that `1` is a constant value needed to perform some operations. I set it as a public value because of the way how the library parses the circuit, to not overcomplicate other parts of the code. Indeed, it is not how other solutions work. Some day I will give it a thought!
